[versions]
jacoco = "0.8.12"
checkstyle = "10.18.0"
# jhipster-needle-gradle-dependency-catalog-version - JHipster will add additional versions for convention plugins heref

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.7.0" }
springdoc-openapi-starter-webflux-api = { module = "org.springdoc:springdoc-openapi-starter-webflux-api", version = "2.6.0" }
commons-beanutils = { module = "commons-beanutils:commons-beanutils", version = "1.9.4" }
# jhipster-needle-gradle-dependency-catalog-libraries - JHipster will add additional libraries versions

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.3" }
# jhipster-needle-gradle-dependency-catalog-plugins - JHipster will add additional plugins versions
