[versions]
jacoco = "0.8.12"
checkstyle = "10.17.0"
# jhipster-needle-gradle-dependency-catalog-version - JHipster will add additional versions for convention plugins heref

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.6.0" }
springdoc-openapi-starter-webflux-api = { module = "org.springdoc:springdoc-openapi-starter-webflux-api", version = "2.5.0" }
mongock-bom = { module = "io.mongock:mongock-bom", version = "5.4.4" }
# jhipster-needle-gradle-dependency-catalog-libraries - JHipster will add additional libraries versions

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.1" }
# jhipster-needle-gradle-dependency-catalog-plugins - JHipster will add additional plugins versions
