# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: school
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
